# Generated by Django 4.0.2 on 2022-06-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_field_one'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='field_one',
            new_name='university',
        ),
    ]
