# Generated by Django 4.0.2 on 2022-06-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_field_one_user_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
