# Generated by Django 4.0.2 on 2022-06-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
